name: Create 404 page, update base href, and deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Replace with your branch name if different

jobs:
  create-404-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
  #    - name: Update base href
  #      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
  #      with:
  #        html_path: 'index.html'
  #        base_href: '/tabito.release/'
          
  #    - name: Add script section to files
  #      run: |
  #        sed -i 's+</head>+<script src="js/redirect.js"></script>\n</head>+' index.html
  #        echo "Script section added to files."

      - name: Create .nojekyll file
        run: |
          touch .nojekyll
          echo ".nojekyll file created."

      - name: Create 404 page
        run: |
          cp index.html 404.html
          echo "404 page created."

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Target branch for deployment
          FOLDER: .  # Folder containing the static files to deploy
