name: Create 404 page, update base href, and deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Replace with your branch name if different

jobs:
  create-404-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
      - name: Update base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: 'index.html'
          base_href: '/tabito.release/'
          
      - name: Add script section to files
        run: |
          sed -i 's+</head>+<script src="js/redirect.js"></script>\n</head>+' index.html
          echo "Script section added to files."

      - name: Create .nojekyll file
        run: |
          touch .nojekyll
          echo ".nojekyll file created."

      - name: Create 404 page
        run: |
          cp index.html 404.html
          echo "404 page created."

      - name: Create 405 page
        run: |
          cp index.html 405.html
          echo "405 page created."
           
      - name: Commit and push changes to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git with GitHub Actions bot user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Checkout the gh-pages branch or create it
          git checkout gh-pages || git checkout --orphan gh-pages

          # Remove all files to start fresh
          git rm -rf .

          # Copy the necessary files to gh-pages
          cp -r ../.github . # Include hidden .github directory
          cp -r . ../.github

          # Add and commit all files
          git add -A
          git commit -m "Deploy to GitHub Pages"

          # Push to the gh-pages branch
          git push -f origin gh-pages
