name: Create 404 page, update base href, and deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Replace with your branch name if different

jobs:
  create-404-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
      - name: Update base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: 'index.html'
          base_href: '/tabito.release/'
          
      - name: Add script section to files
        run: |
          sed -i 's+</head>+<script src="js/redirect.js"></script>\n</head>+' index.html
          echo "Script section added to files."

      - name: Create .nojekyll file
        run: |
          touch .nojekyll
          echo ".nojekyll file created."

      - name: Create 404 page
        run: |
          cp index.html 404.html
          echo "404 page created."

      - name: Create 405 page
        run: |
          cp index.html 405.html
          echo "405 page created."
          
      - name: Commit changes to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html 404.html .nojekyll
          git commit -m "Update index.html, create 404.html and .nojekyll"
          git push origin gh-pages
          
      - name: Commit changes and deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .

      - name: Create 406 page
        run: |
          cp index.html 406.html
          echo "406 page created."
