name: Create 404 page and deploy

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  create-404:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create 404 page
        run: |
          # Copy index.html to 404.html
          cp index.html 404.html
          echo "404 page created."

      - name: Add script section to files
        run: |
          # Add script section to index.html (at the end of the <head> section)
          sed -i 's+</head>+<script src="resources/redirect.js"></script>\n</head>+' index.html
          
          # Add script section to 404.html (assuming same redirect.js is used, at the end of the <head> section)
          sed -i 's+</head>+<script src="resources/redirect.js"></script>\n</head>+' 404.html
          echo "Script section added to files."

      - name: Create .nojekyll file
        run: |
          touch .nojekyll
          echo ".nojekyll file created."

      - name: Deploy to master branch
        if: success()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout master
          git add index.html 404.html resources/redirect.js .nojekyll
          git commit -m "Add redirect.js and update HTML files"
          git push origin master

      # Optional: Add steps for other actions, like testing or notifications
